steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
          # Install jq
          apt-get update && apt-get install -y jq
          
          # Create the scheduled query transfer configuration.
          bq mk \
            --transfer_config \
            --display_name="bq_data_destruction" \
            --params="$(jq -n --rawfile query bq_data_destruction.sql '{query: $query, start_time:"2025-02-06T01:30:00Z"}')" \
            --data_source=scheduled_query \
            --schedule='every day 01:30' \
            --location=US \
            --service_account_name="$SERVICE_ACCOUNT_EMAIL"
options:
  logging: CLOUD_LOGGING_ONLY
