steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Set the correct project explicitly
        gcloud config set project ${PROJECT_ID}
        # Now deploy the scheduled query
        bq query \
          --use_legacy_sql=false \
          --display_name="bq_data_destruction" \
          --schedule='every day 01:30' \
          --replace < bq_data_destruction.sql
options:
  logging: CLOUD_LOGGING_ONLY
