steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
          # Install jq
          apt-get update && apt-get install -y jq
          
          # Update the scheduled query transfer configuration using the pre-defined transfer config ID.
          bq update --transfer_config \
            --params="$(jq -n --rawfile query bq_data_destruction.sql '{query: $query}')" \
            --schedule='every day 01:30' \
            --start_time="$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            --location=US \
            --service_account_name="$SERVICE_ACCOUNT_EMAIL" \
            "${_RESOURCE_NAME}"
options:
  logging: CLOUD_LOGGING_ONLY

