steps:
  - name: "gcr.io/cloud-builders/bq:v2.0.93"
    args:
      - query
      - --use_legacy_sql=false
      - --display_name="bq_data_destruction"
      - --destination_table=""
      - --schedule="cron:30 1 * * *"
      - --replace
      - < bq_data_destruction.sql

options:
  logging: CLOUD_LOGGING_ONLY  # Ensures logs are stored in Cloud Logging