steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
          bq mk \
            --transfer_config \
            --display_name="bq_data_destruction" \
            --params="$(jq -n --rawfile query bq_data_destruction.sql '{query: $query}')" \
            --data_source=scheduled_query \
            --schedule='every day 01:30' \
            --service_account_name="${SERVICE_ACCOUNT_EMAIL}"
options:
  logging: CLOUD_LOGGING_ONLY