steps:
  # Step 1: Install dependencies using a Python image
  - name: "python:3.11"
    entrypoint: "bash"
    args:
      - "-c"
      - "pip install -r requirements.txt"

  # Step 2: Deploy the Cloud Function using gcloud
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "functions"
      - "deploy"
      - "run_bq_data_destruction"
      - "--runtime"
      - "python311"
      - "--trigger-http"
      - "--region"
      - "us-central1"
      - "--entry-point"
      - "run_bq_data_destruction"
      - "--source"
      - "."

options:
  logging: CLOUD_LOGGING_ONLY  # Ensures logs are stored in Cloud Logging
