steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        bq query \
          --use_legacy_sql=false \
          --display_name="bq_data_destruction" \
          --destination_table="" \
          --schedule="cron:30 1 * * *" \
          --replace < delete_flagged_data.sql

options:
  logging: CLOUD_LOGGING_ONLY  # Ensures logs are stored in Cloud Logging
