steps:
  # Step 1: Install dependencies
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - "pip install -r requirements.txt"

  # Step 2: Deploy the Cloud Function
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "functions"
      - "deploy"
      - "run_bq_data_destruction"
      - "--runtime"
      - "python311"
      - "--trigger-http"
      - "--region"
      - "us-central1"
      - "--entry-point"
      - "run_bq_data_destruction"
      - "--source"
      - "."
